# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# include-test-azure-frs

parameters:
- name: poolBuild
  type: object
  default: Lite

- name: testPackage
  type: string

- name: testWorkspace
  type: string

- name: buildDirectory
  type: string

- name: timeoutInMinutes
  type: number
  default: 60

- name: target
  type: string

- name: env
  type: object
  default:

- name: splitTestVariants
  type: object
  default:
  - ""

jobs:
  - ${{ each variant in parameters.splitTestVariants }}:
    - job:
      displayName: Run ${{ variant }}
      pool: ${{ parameters.poolBuild }}
      timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
      variables:
      # We use 'chalk' to colorize output, which auto-detects color support in the
      # running terminal.  The log output shown in Azure DevOps job runs only has
      # basic ANSI color support though, so force that in the pipeline
      - name: FORCE_COLOR
        value: 1
      - name: testPackageDir
        value: '${{ parameters.testWorkspace }}'
      - name: skipComponentGovernanceDetection
        value: true
      - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/test/') }}:
        - name: feed
          value: https://pkgs.dev.azure.com/fluidframework/internal/_packaging/internal/npm/registry/
      - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/test/')) }}:
        - name: feed
          value: https://pkgs.dev.azure.com/fluidframework/internal/_packaging/build/npm/registry/

      steps:
      # Setup
      - checkout: none
        clean: true

      # Print parameters/Vars
      - task: Bash@3
        displayName: Print Parameters and Variables
        inputs:
          targetType: 'inline'
          script: |
            # Show all task group conditions
            echo "
            Pipeline Parameters:
              poolBuild=${{ parameters.poolBuild }}
              testPackage=${{ parameters.testPackage }}
            Pipeline Variables:
              testWorkspace=${{ parameters.testWorkspace }}
              testPackageFilePattern=${{ variables.testPackageFilePattern }}
              feed=${{ variables.feed }}
              target=${{ parameters.target }}
              variant=${{ variant }}
              buildDirectory=${{ parameters.buildDirectory }}
            "
      # Install
      - task: UseNode@1
        displayName: Use Node 12.x
        inputs:
          version: 12.x

      # Download artifact
      - task: DownloadPipelineArtifact@2
        displayName: Download test package
        inputs:
          source: specific
          project: internal
          pipeline: Build - client packages
          preferTriggeringPipeline: true
          runVersion: latestFromBranch
          runBranch: $(Build.SourceBranch)
          artifact: pack-azure-frs-test
          path: $(Pipeline.Workspace)/azure-frs-test

      # Create test directory and unpack package
      - task: Bash@3
        displayName: Create test directory and unpack package
        inputs:
          targetType: 'inline'
          script: |
            mkdir ${{ parameters.testWorkspace }}

      # Unpack package
      - task: Bash@3
        displayName: Create test directory and unpack package
        inputs:
          workingDir: ${{ parameters.testWorkspace }}
          targetType: 'inline'
          script: |
            tar -xvf $(Pipeline.Workspace)/azure-frs-test/azure-client.tgz


      # Run the tests
      - task: Npm@1
        displayName: '[azure-client tests] npm run test:realsvc:${{ parameters.target }} ${{ variant }}'
        continueOnError: true
        env:
          ${{ parameters.env }}
        inputs:
          command: 'custom'
          workingDir: ${{ parameters.buildDirectory }}/packages/framework/azure-client
          customCommand: 'run test:realsvc:${{ parameters.target }} -- ${{ variant }}'

      # Upload results
      - task: PublishTestResults@2
        displayName: Publish Test Results
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/*junit-report.xml'
          searchFolder: ${{ variables.testPackageDir }}/nyc
          mergeTestResults: false
        condition: succeededOrFailed()
