# Copyright (c) Microsoft Corporation and contributors. All rights reserved.
# Licensed under the MIT License.

# test-azure-frs pipeline

name: $(Build.BuildId)

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: client   # Name of the pipeline resource
    source: Build - client packages
    trigger:
      branches:
      - releases/*
      - main
      paths:
        include:
        - packages/framework/azure-client
        - packages/drivers/routerlicious-driver
        # Add more dependencies of AzureClient here
        - tools/pipelines/test-azure-frs.yml
        - tools/pipelines/templates/include-test-real-service.yml

variables:
- group: prague-key-vault
- name: testWorkspace
  value: $(Pipeline.Workspace)/test

stages:
  # Run Azure FRS Tests
  - stage:
    displayName: e2e - azure
    dependsOn: []
    jobs:
    - template: templates/include-test-real-service.yml
      parameters:
        poolBuild: Lite
        testPackage: "@fluidframework/azure-client"
        testWorkspace: ${{ variables.testWorkspace }}
        testCommand: test:realsvc:azure
        downloadTestFiles: true
        env:
          FLUID_TEST_LOGGER_PKG_PATH: ${{ variables.testWorkspace }}/node_modules/@ff-internal/aria-logger # Contains getTestLogger impl to inject
          azure__fluid__relay__service__tenantId: $(azure-fluid-relay-service-tenantId)
          azure__fluid__relay__service__function__url: $(azure-fluid-relay-service-function-url)
