name: "Auto Assign Pull Request"
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
    - main
    - release/*

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: mszostok/codeowners-validator@v0.6.0
      with:
        experimental_checks: "notowned"
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      env: # Add environment variables here
        OWNER_CHECKER_IGNORED_OWNERS: "nedalhy,ruiterr"
        NOT_OWNED_CHECKER_SKIP_PATTERNS: "/*.*"
    - uses: open-telemetry/assign-reviewers-action@main
      with:
        config-file: '.github/code_owners.yml'
        # repo-token: ${{ secrets.GITHUB_TOKEN }}
        assign-users: false
        request-user-reviews: false
